### PR TITLE
Add immutable widget test

### PR DESCRIPTION
**Pull request by samdark**
| Q             | A
| ------------- | ---
| Is bugfix?    | ✔️
| New feature?  | ❌
| Breaks BC?    | ✔️
| Fixed issues  | https://github.com/yiisoft/yii-bulma/pull/20

### CODE REVIEW

**Comment by samdark** [comment]
I see two ways to deal with it:

1. Say widgets should be mutable.
2. Make `end()` non-static as done in https://github.com/yiisoft/widget/pull/21/commits/8cb3ca3cd77b1f00ab7e94461771fc32f13764cc

Second way is better, I think.

**Review by rustamwin — APPROVED** [review]

**Comment by samdark** [comment]
Alternative from @xepozz:

```php
$widget = $widgetFactory->create(MyWidget::class, $params);
$widget->end();
```

**Comment by xepozz** [comment]
`end()` looks useless because it can be replaced to `__toString()`
```php
$widget = $widgetFactory->create(MyWidget::class, $params);
echo $widget;
```

**Comment by samdark** [comment]
https://github.com/yiisoft/widget/pull/22

**Pull request closed without merging**
